spring:
  datasource:
    # postgres
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 初始数据
    schema: classpath:db/mysql/init.sql
    data: classpath:db/mysql/data.sql

# Logger
logging:
  level:
    com: info
    org: info