# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8082

spring:
  application:
    name: backup
  boot:
    admin:
      client:
        url: http://localhost:8000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# datasource
datasource:
  host: localhost
  username: root
  password: root
  database: demo
