# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8082
  context-path: /backup

  spirng:
    application:
      name: backup

# datasource
datasource:
  host: localhost
  username: root
  password: root
  database: test
