spring:
  datasource:
    # mysql
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600000 # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      max-lifetime: 18000000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
      connection-test-query: SELECT 1
      validation-timeout: 3000

  # cache
  redis:
    host: 127.0.0.1
    username: default
    password: redispw
    port: 6379
    timeout: 10000
    type: redis
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0